### ISSUE TITLE
Error while executing the same in local

### ISSUE THREAD

**Issue by sandeep540** [twalthr/flink-api-examples#1]
I cloned the repo in Intellij and running locally, I am getting below error

```
/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=52479:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/charsets.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/cldrdata.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/dnsns.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/jaccess.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/localedata.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/nashorn.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/sunec.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/ext/zipfs.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/jce.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/jfr.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/jsse.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/management-agent.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/resources.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/jre/lib/rt.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/lib/dt.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/lib/jconsole.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/lib/sa-jdi.jar:/Users/sandeep/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_292/Contents/Home/lib/tools.jar:/Users/sandeep/IdeaProjects/flink-api-examples/target/classes:/Users/sandeep/.m2/repository/org/apache/flink/flink-java/1.15-SNAPSHOT/flink-java-1.15-20211106.210440-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-core/1.15-SNAPSHOT/flink-core-1.15-20211106.210425-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-annotations/1.15-SNAPSHOT/flink-annotations-1.15-20211106.210327-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-metrics-core/1.15-SNAPSHOT/flink-metrics-core-1.15-20211106.210343-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-shaded-asm-7/7.1-14.0/flink-shaded-asm-7-7.1-14.0.jar:/Users/sandeep/.m2/repository/com/esotericsoftware/kryo/kryo/2.24.0/kryo-2.24.0.jar:/Users/sandeep/.m2/repository/com/esotericsoftware/minlog/minlog/1.2/minlog-1.2.jar:/Users/sandeep/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/Users/sandeep/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/sandeep/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/Users/sandeep/.m2/repository/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:/Users/sandeep/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar:/Users/sandeep/.m2/repository/com/twitter/chill-java/0.7.6/chill-java-0.7.6.jar:/Users/sandeep/.m2/repository/org/slf4j/slf4j-api/1.7.15/slf4j-api-1.7.15.jar:/Users/sandeep/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-shaded-force-shading/14.0/flink-shaded-force-shading-14.0.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-streaming-java_2.12/1.15-SNAPSHOT/flink-streaming-java_2.12-1.15-20211025.201001-59.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-file-sink-common/1.15-SNAPSHOT/flink-file-sink-common-1.15-20211106.210913-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-runtime/1.15-SNAPSHOT/flink-runtime-1.15-20211106.210849-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-rpc-core/1.15-SNAPSHOT/flink-rpc-core-1.15-20211106.210700-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-rpc-akka-loader/1.15-SNAPSHOT/flink-rpc-akka-loader-1.15-20211106.210720-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-queryable-state-client-java/1.15-SNAPSHOT/flink-queryable-state-client-java-1.15-20211106.210726-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-hadoop-fs/1.15-SNAPSHOT/flink-hadoop-fs-1.15-20211106.210540-104.jar:/Users/sandeep/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-shaded-netty/4.1.65.Final-14.0/flink-shaded-netty-4.1.65.Final-14.0.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-shaded-jackson/2.12.4-14.0/flink-shaded-jackson-2.12.4-14.0.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-shaded-zookeeper-3/3.4.14-14.0/flink-shaded-zookeeper-3-3.4.14-14.0.jar:/Users/sandeep/.m2/repository/org/javassist/javassist/3.24.0-GA/javassist-3.24.0-GA.jar:/Users/sandeep/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.3/snappy-java-1.1.8.3.jar:/Users/sandeep/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-scala_2.12/1.15-SNAPSHOT/flink-scala_2.12-1.15-20211106.210532-71.jar:/Users/sandeep/.m2/repository/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar:/Users/sandeep/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar:/Users/sandeep/.m2/repository/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar:/Users/sandeep/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar:/Users/sandeep/.m2/repository/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-shaded-guava/30.1.1-jre-14.0/flink-shaded-guava-30.1.1-jre-14.0.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-clients_2.12/1.15-SNAPSHOT/flink-clients_2.12-1.15-20211025.201012-59.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-optimizer/1.15-SNAPSHOT/flink-optimizer-1.15-20211106.210907-104.jar:/Users/sandeep/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-api-java-bridge_2.12/1.15-SNAPSHOT/flink-table-api-java-bridge_2.12-1.15-20211025.201929-59.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-api-java/1.15-SNAPSHOT/flink-table-api-java-1.15-20211106.211824-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-planner_2.12/1.15-SNAPSHOT/flink-table-planner_2.12-1.15-20211106.212339-71.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-common/1.15-SNAPSHOT/flink-table-common-1.15-20211106.211814-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-connector-files/1.15-SNAPSHOT/flink-connector-files-1.15-20211106.211540-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-api-scala_2.12/1.15-SNAPSHOT/flink-table-api-scala_2.12-1.15-20211106.211851-71.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-api-java-bridge/1.15-SNAPSHOT/flink-table-api-java-bridge-1.15-20211106.211831-12.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-streaming-java/1.15-SNAPSHOT/flink-streaming-java-1.15-20211106.210944-12.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-api-scala-bridge_2.12/1.15-SNAPSHOT/flink-table-api-scala-bridge_2.12-1.15-20211106.211907-71.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-streaming-scala_2.12/1.15-SNAPSHOT/flink-streaming-scala_2.12-1.15-20211106.211743-71.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-runtime_2.12/1.15-SNAPSHOT/flink-table-runtime_2.12-1.15-20211106.212012-71.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-table-code-splitter/1.15-SNAPSHOT/flink-table-code-splitter-1.15-20211106.211942-104.jar:/Users/sandeep/.m2/repository/org/codehaus/janino/janino/3.0.11/janino-3.0.11.jar:/Users/sandeep/.m2/repository/org/codehaus/janino/commons-compiler/3.0.11/commons-compiler-3.0.11.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-connector-kafka_2.12/1.15-SNAPSHOT/flink-connector-kafka_2.12-1.15-20211025.202836-59.jar:/Users/sandeep/.m2/repository/org/apache/kafka/kafka-clients/2.4.1/kafka-clients-2.4.1.jar:/Users/sandeep/.m2/repository/com/github/luben/zstd-jni/1.4.3-1/zstd-jni-1.4.3-1.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-connector-base/1.15-SNAPSHOT/flink-connector-base-1.15-20211106.211535-104.jar:/Users/sandeep/.m2/repository/org/apache/flink/flink-json/1.15-SNAPSHOT/flink-json-1.15-20211106.212349-104.jar:/Users/sandeep/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.14.1/log4j-slf4j-impl-2.14.1.jar:/Users/sandeep/.m2/repository/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar:/Users/sandeep/.m2/repository/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar:/Users/sandeep/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar:/Users/sandeep/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar:/Users/sandeep/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.jar:/Users/sandeep/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.jar com.ververica.Example_02_Table_Motivation
Exception in thread "main" java.lang.RuntimeException: Failed to fetch next result
	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.nextResultFromFetcher(CollectResultIterator.java:109)
	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.hasNext(CollectResultIterator.java:80)
	at org.apache.flink.table.planner.connectors.CollectDynamicSink$CloseableRowIteratorWrapper.hasNext(CollectDynamicSink.java:188)
	at org.apache.flink.table.utils.PrintUtils.printAsTableauForm(PrintUtils.java:154)
	at org.apache.flink.table.api.internal.TableResultImpl.print(TableResultImpl.java:157)
	at com.ververica.Example_02_Table_Motivation.main(Example_02_Table_Motivation.java:22)
Caused by: java.io.IOException: Failed to fetch job execution result
	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.getAccumulatorResults(CollectResultFetcher.java:184)
	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.next(CollectResultFetcher.java:121)
	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.nextResultFromFetcher(CollectResultIterator.java:106)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.getAccumulatorResults(CollectResultFetcher.java:182)
	... 7 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
	at org.apache.flink.runtime.minicluster.MiniClusterJobClient.lambda$getJobExecutionResult$3(MiniClusterJobClient.java:137)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
	at org.apache.flink.runtime.minicluster.MiniClusterJobClient.getJobExecutionResult(MiniClusterJobClient.java:134)
	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.getAccumulatorResults(CollectResultFetcher.java:181)
	... 7 more
Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:249)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:239)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:230)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:681)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:79)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:445)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:316)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:314)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.NoSuchMethodError: org.apache.flink.runtime.execution.Environment.getThroughputCalculator()Lorg/apache/flink/runtime/throughput/ThroughputCalculator;
	at org.apache.flink.streaming.runtime.tasks.StreamTask.<init>(StreamTask.java:430)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.<init>(StreamTask.java:361)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.<init>(SourceStreamTask.java:101)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.<init>(SourceStreamTask.java:97)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.flink.runtime.taskmanager.Task.loadAndInstantiateInvokable(Task.java:1580)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:726)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1
```

**Comment by sandeep540** [comment]
@twalthr Any help will be approeciated

**Comment by twalthr** [comment]
@sandeep540 might be related to the fact that the repo is based on a nightly snapshot.Removing some of the Scala suffixes in pom.xml can help, because the community is currently isolating Scala in the core a bit. I will update the repo shortly for 1.15.

**Comment by twalthr** [comment]
I updated the examples to a non-snapshot version until 1.15 is released:
3833f6720849bfb1fc907a55ce2ab949af5fc874
